export const SKIP_TAGS = new Set([
  "SCRIPT",
  "STYLE",
  "INPUT",
  "TEXTAREA",
  "BUTTON",
  "SELECT",
  "OPTION",
  "SVG",
  "CANVAS",
  "VIDEO",
  "AUDIO",
  "SOURCE",
  "TRACK",
  "IFRAME",
  "NOSCRIPT",
  "PRE",
  "CODE",
])

export const TRANSLATABLE_BLOCK_SELECTOR = [
  "header a",
  "nav a",
  "footer a",
  "article h1",
  "article h2",
  "article h3",
  "article h4",
  "article h5",
  "article h6",
  "article p",
  "article li > a",
  "article li",
  "article blockquote",
  "article figcaption",
  "main h1",
  "main h2",
  "main h3",
  "main h4",
  "main h5",
  "main h6",
  "main p",
  "main li > a",
  "main li",
  "main blockquote",
  "main figcaption",
  "[role='main'] h1",
  "[role='main'] h2",
  "[role='main'] h3",
  "[role='main'] h4",
  "[role='main'] h5",
  "[role='main'] h6",
  "[role='main'] p",
  "[role='main'] li > a",
  "[role='main'] li",
  "[role='main'] blockquote",
  "[role='main'] figcaption",
  "body h1",
  "body h2",
  "body h3",
  "body h4",
  "body h5",
  "body h6",
  "body p",
  "body li > a",
  "body li",
  "body blockquote",
].join(",")

export const OPENREAD_WRAPPER_CLASS = "openread-translation-wrapper"
export const OPENREAD_SOURCE_CLASS = "openread-source-wrapper"
export const OPENREAD_LOADING_CLASS = "openread-translation-loading"
export const OPENREAD_ERROR_CLASS = "openread-translation-error"
export const OPENREAD_PROGRESS_CLASS = "openread-progress-chip"
export const OPENREAD_INPUT_STATUS_CLASS = "openread-input-status"
export const OPENREAD_SELECTION_CARD_CLASS = "openread-selection-card"
